# -*- coding: utf-8 -*-
"""Amazon_Go

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17A3QYWXHWokgns0R8Sm3q1Xtka5cMpP1
"""

import cv2
import numpy

!git clone https://github.com/ultralytics/yolov3

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov3/
# %ls

# Commented out IPython magic to ensure Python compatibility.
# %pip install -r requirements.txt

import torch

!python detect.py --source 'images.jpg'

!python detect.py --source 'test.mp4'
